name: Deploy NodeJS Application to Hostinger

on:
  push:
    branches:
      - vps-deploy
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: devop                 
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/devop/crm  
            git pull
            docker compose up -d --build
